/* Generated By:JavaCC: Do not edit this line. Gramatica.java */
package Analizador;
public class Gramatica implements GramaticaConstants {

/** Fin Lexico */
  final public void principal() throws ParseException {
    jj_consume_token(PACKAGE);
    jj_consume_token(IDENTIFICADOR);
    if (jj_2_1(4)) {
      imports();
    } else {
      ;
    }
    function();
  }

  final public void imports() throws ParseException {
    jj_consume_token(IMPORT);
    if (jj_2_3(4)) {
      jj_consume_token(STRING_VALOR);
    } else if (jj_2_4(4)) {
      jj_consume_token(PAPERTURA);
      label_1:
      while (true) {
        jj_consume_token(STRING_VALOR);
        if (jj_2_2(4)) {
          ;
        } else {
          break label_1;
        }
      }
      jj_consume_token(PCIERRE);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void function() throws ParseException {
    jj_consume_token(FUNCTION);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(PAPERTURA);
    if (jj_2_6(4)) {
      label_2:
      while (true) {
        listaIdentificadores();
        tipoDato();
        if (jj_2_5(4)) {
          ;
        } else {
          break label_2;
        }
      }
    } else {
      ;
    }
    jj_consume_token(PCIERRE);
    if (jj_2_7(4)) {
      tipoDato();
    } else {
      ;
    }
    jj_consume_token(LLAVEAPERTURA);
    label_3:
    while (true) {
      sentencias();
      if (jj_2_8(4)) {
        ;
      } else {
        break label_3;
      }
    }
    if (jj_2_9(4)) {
      jj_consume_token(RETURN);
      listaValores();
    } else {
      ;
    }
    jj_consume_token(LLAVECIERRE);
  }

  final public void sentencias() throws ParseException {
    if (jj_2_10(4)) {
      declararVariable();
    } else if (jj_2_11(4)) {
      declaracionIdentificador();
    } else if (jj_2_12(4)) {
      controlIf();
    } else if (jj_2_13(4)) {
      For();
    } else if (jj_2_14(4)) {
      arreglos();
    } else if (jj_2_15(4)) {
      controlSwitch();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void declararVariable() throws ParseException {
    jj_consume_token(VAR);
    listaIdentificadores();
    tipoDato();
    if (jj_2_16(4)) {
      jj_consume_token(ASIGNACION);
      listaValores();
    } else {
      ;
    }
  }

  final public void listaIdentificadores() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    label_4:
    while (true) {
      if (jj_2_17(4)) {
        ;
      } else {
        break label_4;
      }
      jj_consume_token(COMA);
      jj_consume_token(IDENTIFICADOR);
    }
  }

  final public void valor() throws ParseException {
    if (jj_2_19(4)) {
      jj_consume_token(STRING_VALOR);
    } else if (jj_2_20(4)) {
      jj_consume_token(INT_VALOR);
    } else if (jj_2_21(4)) {
      jj_consume_token(FLOAT_VALOR);
    } else if (jj_2_22(4)) {
      jj_consume_token(IDENTIFICADOR);
      if (jj_2_18(4)) {
        jj_consume_token(CORAPERTURA);
        jj_consume_token(INT_VALOR);
        jj_consume_token(CORCIERRE);
      } else {
        ;
      }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void listaValores() throws ParseException {
    opSimple();
    label_5:
    while (true) {
      if (jj_2_23(4)) {
        ;
      } else {
        break label_5;
      }
      jj_consume_token(COMA);
      opSimple();
    }
  }

  final public void tipoDato() throws ParseException {
    if (jj_2_24(4)) {
      jj_consume_token(INT);
    } else if (jj_2_25(4)) {
      jj_consume_token(STRING);
    } else if (jj_2_26(4)) {
      jj_consume_token(FLOAT);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void declaracionIdentificador() throws ParseException {
    if (jj_2_27(2147483647)) {
      asignacionVariableMultiple();
    } else if (jj_2_28(2147483647)) {
      asignacionVariableCorta();
    } else if (jj_2_29(2147483647)) {
      imprimir();
    } else if (jj_2_30(2147483647)) {
      asignacionVariable();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void asignacionVariable() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    if (jj_2_31(4)) {
      jj_consume_token(ASIGNACIONSUMA);
    } else if (jj_2_32(4)) {
      jj_consume_token(ASIGNACIONRESTA);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    opSimple();
  }

  final public void asignacionVariableMultiple() throws ParseException {
    listaIdentificadores();
    jj_consume_token(ASIGNACION);
    listaValores();
  }

  final public void asignacionVariableCorta() throws ParseException {
    listaIdentificadores();
    jj_consume_token(ASIGNACIONCORTA);
    listaValores();
  }

  final public void opSimple() throws ParseException {
    if (jj_2_33(4)) {
      valor();
    } else if (jj_2_34(4)) {
      opParentesis();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_6:
    while (true) {
      if (jj_2_35(4)) {
        ;
      } else {
        break label_6;
      }
      if (jj_2_38(4)) {
        if (jj_2_36(4)) {
          opAritmetico();
        } else if (jj_2_37(4)) {
          opBit();
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
        valor();
      } else if (jj_2_39(4)) {
        opParentesis();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void opParentesis() throws ParseException {
    jj_consume_token(PAPERTURA);
    opSimple();
    jj_consume_token(PCIERRE);
  }

  final public void opAritmetico() throws ParseException {
    if (jj_2_40(4)) {
      jj_consume_token(SUMA);
    } else if (jj_2_41(4)) {
      jj_consume_token(RESTA);
    } else if (jj_2_42(4)) {
      jj_consume_token(MULTIPLICACION);
    } else if (jj_2_43(4)) {
      jj_consume_token(MOD);
    } else if (jj_2_44(4)) {
      jj_consume_token(INCREMENTO);
    } else if (jj_2_45(4)) {
      jj_consume_token(DECREMENTO);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void controlIf() throws ParseException {
    jj_consume_token(IF);
    if (jj_2_46(4)) {
      condicion();
    } else if (jj_2_47(4)) {
      jj_consume_token(IDENTIFICADOR);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(LLAVEAPERTURA);
    label_7:
    while (true) {
      sentencias();
      if (jj_2_48(4)) {
        ;
      } else {
        break label_7;
      }
    }
    jj_consume_token(LLAVECIERRE);
    if (jj_2_49(4)) {
      controlElse();
    } else {
      ;
    }
  }

  final public void controlElse() throws ParseException {
    jj_consume_token(ELSE);
    jj_consume_token(LLAVEAPERTURA);
    label_8:
    while (true) {
      sentencias();
      if (jj_2_50(4)) {
        ;
      } else {
        break label_8;
      }
    }
    jj_consume_token(LLAVECIERRE);
  }

  final public void condicion() throws ParseException {
    condicionSimple();
    label_9:
    while (true) {
      if (jj_2_51(4)) {
        ;
      } else {
        break label_9;
      }
      opLogico();
      if (jj_2_52(4)) {
        condicionSimple();
      } else if (jj_2_53(4)) {
        jj_consume_token(IDENTIFICADOR);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void condicionSimple() throws ParseException {
    opSimple();
    opRelacional();
    opSimple();
  }

  final public void opLogico() throws ParseException {
    if (jj_2_54(4)) {
      jj_consume_token(AND);
    } else if (jj_2_55(4)) {
      jj_consume_token(OR);
    } else if (jj_2_56(4)) {
      jj_consume_token(NOT);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void opRelacional() throws ParseException {
    if (jj_2_59(4)) {
      jj_consume_token(MAYOR);
      if (jj_2_57(4)) {
        jj_consume_token(ASIGNACION);
      } else {
        ;
      }
    } else if (jj_2_60(4)) {
      jj_consume_token(MENOR);
      if (jj_2_58(4)) {
        jj_consume_token(ASIGNACION);
      } else {
        ;
      }
    } else if (jj_2_61(4)) {
      jj_consume_token(IGUAL);
    } else if (jj_2_62(4)) {
      jj_consume_token(DIFERENTE);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void opBit() throws ParseException {
    if (jj_2_63(4)) {
      jj_consume_token(BITAND);
    } else if (jj_2_64(4)) {
      jj_consume_token(BITOR);
    } else if (jj_2_65(4)) {
      jj_consume_token(BITXOR);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void For() throws ParseException {
    if (jj_2_66(2147483647)) {
      forCompleto();
    } else if (jj_2_67(2147483647)) {
      forCondicional();
    } else if (jj_2_68(2147483647)) {
      forInfinito();
    } else if (jj_2_69(2147483647)) {
      forRange();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void forCompleto() throws ParseException {
    jj_consume_token(FOR);
    asignacionVariableCorta();
    jj_consume_token(PCOMA);
    condicion();
    jj_consume_token(PCOMA);
    valor();
    opAritmetico();
    jj_consume_token(LLAVEAPERTURA);
    label_10:
    while (true) {
      sentencias();
      if (jj_2_70(4)) {
        ;
      } else {
        break label_10;
      }
    }
    jj_consume_token(LLAVECIERRE);
  }

  final public void forCondicional() throws ParseException {
    jj_consume_token(FOR);
    condicion();
    jj_consume_token(LLAVEAPERTURA);
    label_11:
    while (true) {
      sentencias();
      if (jj_2_71(4)) {
        ;
      } else {
        break label_11;
      }
    }
    jj_consume_token(LLAVECIERRE);
  }

  final public void forInfinito() throws ParseException {
    jj_consume_token(FOR);
    jj_consume_token(LLAVEAPERTURA);
    label_12:
    while (true) {
      sentencias();
      if (jj_2_72(4)) {
        ;
      } else {
        break label_12;
      }
    }
    jj_consume_token(LLAVECIERRE);
  }

  final public void forRange() throws ParseException {
    jj_consume_token(FOR);
    if (jj_2_73(4)) {
      jj_consume_token(IDENTIFICADOR);
    } else if (jj_2_74(4)) {
      jj_consume_token(GUIONBAJO);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(COMA);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(ASIGNACIONCORTA);
    jj_consume_token(RANGE);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(LLAVEAPERTURA);
    label_13:
    while (true) {
      sentencias();
      if (jj_2_75(4)) {
        ;
      } else {
        break label_13;
      }
    }
    jj_consume_token(LLAVECIERRE);
  }

  final public void imprimir() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(PUNTO);
    if (jj_2_76(4)) {
      jj_consume_token(PRINTLN);
    } else if (jj_2_77(4)) {
      jj_consume_token(PRINT);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PAPERTURA);
    valor();
    label_14:
    while (true) {
      if (jj_2_78(4)) {
        ;
      } else {
        break label_14;
      }
      jj_consume_token(COMA);
      valor();
    }
    jj_consume_token(PCIERRE);
  }

  final public void arreglos() throws ParseException {
    if (jj_2_79(2147483647)) {
      declararAsignarArreglos();
    } else if (jj_2_80(2147483647)) {
      declararArreglos();
    } else if (jj_2_81(2147483647)) {
      asignarArreglo();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void declararArreglos() throws ParseException {
    jj_consume_token(VAR);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(CORAPERTURA);
    jj_consume_token(INT_VALOR);
    jj_consume_token(CORCIERRE);
    tipoDato();
  }

  final public void asignarArreglo() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(CORAPERTURA);
    jj_consume_token(INT_VALOR);
    jj_consume_token(CORCIERRE);
    jj_consume_token(ASIGNACION);
    opSimple();
  }

  final public void declararAsignarArreglos() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(ASIGNACIONCORTA);
    jj_consume_token(CORAPERTURA);
    jj_consume_token(INT_VALOR);
    jj_consume_token(CORCIERRE);
    tipoDato();
    jj_consume_token(LLAVEAPERTURA);
    listaValores();
    jj_consume_token(LLAVECIERRE);
  }

  final public void controlSwitch() throws ParseException {
    jj_consume_token(SWITCH);
    if (jj_2_82(4)) {
      jj_consume_token(IDENTIFICADOR);
    } else {
      ;
    }
    jj_consume_token(LLAVEAPERTURA);
    label_15:
    while (true) {
      controlCase();
      if (jj_2_83(4)) {
        ;
      } else {
        break label_15;
      }
    }
    if (jj_2_85(4)) {
      jj_consume_token(DEFECTO);
      jj_consume_token(PUNTOS);
      label_16:
      while (true) {
        sentencias();
        if (jj_2_84(4)) {
          ;
        } else {
          break label_16;
        }
      }
    } else {
      ;
    }
    jj_consume_token(LLAVECIERRE);
  }

  final public void controlCase() throws ParseException {
    jj_consume_token(CASE);
    if (jj_2_86(4)) {
      condicion();
    } else if (jj_2_87(4)) {
      valor();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PUNTOS);
    label_17:
    while (true) {
      sentencias();
      if (jj_2_88(4)) {
        ;
      } else {
        break label_17;
      }
    }
    if (jj_2_89(4)) {
      jj_consume_token(FALLTHROUGH);
    } else {
      ;
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  private boolean jj_2_37(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_37(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(36, xla); }
  }

  private boolean jj_2_38(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_38(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(37, xla); }
  }

  private boolean jj_2_39(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_39(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(38, xla); }
  }

  private boolean jj_2_40(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_40(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(39, xla); }
  }

  private boolean jj_2_41(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_41(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(40, xla); }
  }

  private boolean jj_2_42(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_42(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(41, xla); }
  }

  private boolean jj_2_43(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_43(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(42, xla); }
  }

  private boolean jj_2_44(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_44(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(43, xla); }
  }

  private boolean jj_2_45(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_45(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(44, xla); }
  }

  private boolean jj_2_46(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_46(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(45, xla); }
  }

  private boolean jj_2_47(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_47(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(46, xla); }
  }

  private boolean jj_2_48(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_48(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(47, xla); }
  }

  private boolean jj_2_49(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_49(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(48, xla); }
  }

  private boolean jj_2_50(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_50(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(49, xla); }
  }

  private boolean jj_2_51(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_51(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(50, xla); }
  }

  private boolean jj_2_52(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_52(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(51, xla); }
  }

  private boolean jj_2_53(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_53(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(52, xla); }
  }

  private boolean jj_2_54(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_54(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(53, xla); }
  }

  private boolean jj_2_55(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_55(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(54, xla); }
  }

  private boolean jj_2_56(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_56(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(55, xla); }
  }

  private boolean jj_2_57(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_57(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(56, xla); }
  }

  private boolean jj_2_58(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_58(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(57, xla); }
  }

  private boolean jj_2_59(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_59(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(58, xla); }
  }

  private boolean jj_2_60(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_60(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(59, xla); }
  }

  private boolean jj_2_61(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_61(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(60, xla); }
  }

  private boolean jj_2_62(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_62(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(61, xla); }
  }

  private boolean jj_2_63(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_63(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(62, xla); }
  }

  private boolean jj_2_64(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_64(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(63, xla); }
  }

  private boolean jj_2_65(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_65(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(64, xla); }
  }

  private boolean jj_2_66(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_66(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(65, xla); }
  }

  private boolean jj_2_67(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_67(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(66, xla); }
  }

  private boolean jj_2_68(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_68(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(67, xla); }
  }

  private boolean jj_2_69(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_69(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(68, xla); }
  }

  private boolean jj_2_70(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_70(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(69, xla); }
  }

  private boolean jj_2_71(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_71(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(70, xla); }
  }

  private boolean jj_2_72(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_72(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(71, xla); }
  }

  private boolean jj_2_73(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_73(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(72, xla); }
  }

  private boolean jj_2_74(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_74(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(73, xla); }
  }

  private boolean jj_2_75(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_75(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(74, xla); }
  }

  private boolean jj_2_76(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_76(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(75, xla); }
  }

  private boolean jj_2_77(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_77(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(76, xla); }
  }

  private boolean jj_2_78(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_78(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(77, xla); }
  }

  private boolean jj_2_79(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_79(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(78, xla); }
  }

  private boolean jj_2_80(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_80(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(79, xla); }
  }

  private boolean jj_2_81(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_81(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(80, xla); }
  }

  private boolean jj_2_82(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_82(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(81, xla); }
  }

  private boolean jj_2_83(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_83(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(82, xla); }
  }

  private boolean jj_2_84(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_84(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(83, xla); }
  }

  private boolean jj_2_85(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_85(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(84, xla); }
  }

  private boolean jj_2_86(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_86(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(85, xla); }
  }

  private boolean jj_2_87(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_87(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(86, xla); }
  }

  private boolean jj_2_88(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_88(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(87, xla); }
  }

  private boolean jj_2_89(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_89(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(88, xla); }
  }

  private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_40()) {
    jj_scanpos = xsp;
    if (jj_3_41()) {
    jj_scanpos = xsp;
    if (jj_3_42()) {
    jj_scanpos = xsp;
    if (jj_3_43()) {
    jj_scanpos = xsp;
    if (jj_3_44()) {
    jj_scanpos = xsp;
    if (jj_3_45()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_22() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_18()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_40() {
    if (jj_scan_token(SUMA)) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_scan_token(PAPERTURA)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(PCIERRE)) return true;
    return false;
  }

  private boolean jj_3_31() {
    if (jj_scan_token(ASIGNACIONSUMA)) return true;
    return false;
  }

  private boolean jj_3_36() {
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3_35() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_38()) {
    jj_scanpos = xsp;
    if (jj_3_39()) return true;
    }
    return false;
  }

  private boolean jj_3_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_36()) {
    jj_scanpos = xsp;
    if (jj_3_37()) return true;
    }
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_33() {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3R_29() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_33()) {
    jj_scanpos = xsp;
    if (jj_3_34()) return true;
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_35()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_3R_19()) return true;
    if (jj_scan_token(ASIGNACIONCORTA)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_16() {
    if (jj_scan_token(ASIGNACION)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_21() {
    if (jj_scan_token(FLOAT_VALOR)) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_3R_19()) return true;
    if (jj_scan_token(ASIGNACION)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_30() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(37)) {
    jj_scanpos = xsp;
    if (jj_scan_token(38)) return true;
    }
    return false;
  }

  private boolean jj_3_29() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(PUNTO)) return true;
    return false;
  }

  private boolean jj_3_26() {
    if (jj_scan_token(FLOAT)) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_31()) {
    jj_scanpos = xsp;
    if (jj_3_32()) return true;
    }
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_28() {
    if (jj_3R_19()) return true;
    if (jj_scan_token(ASIGNACIONCORTA)) return true;
    return false;
  }

  private boolean jj_3_27() {
    if (jj_3R_19()) return true;
    if (jj_scan_token(ASIGNACION)) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_56()) return true;
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_3R_55()) return true;
    return false;
  }

  private boolean jj_3_25() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3_23() {
    if (jj_scan_token(COMA)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_20() {
    if (jj_scan_token(INT_VALOR)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_19()) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3_6() {
    Token xsp;
    if (jj_3_5()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_5()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_17() {
    if (jj_scan_token(COMA)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_3R_54()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(STRING_VALOR)) return true;
    return false;
  }

  private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_24()) {
    jj_scanpos = xsp;
    if (jj_3_25()) {
    jj_scanpos = xsp;
    if (jj_3_26()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_24() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_3R_29()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_23()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_19()) {
    jj_scanpos = xsp;
    if (jj_3_20()) {
    jj_scanpos = xsp;
    if (jj_3_21()) {
    jj_scanpos = xsp;
    if (jj_3_22()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3_78() {
    if (jj_scan_token(COMA)) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_scan_token(STRING_VALOR)) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(PAPERTURA)) return true;
    Token xsp;
    if (jj_3_2()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_2()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(PCIERRE)) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_17()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_scan_token(VAR)) return true;
    if (jj_3R_19()) return true;
    if (jj_3R_20()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_16()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_87() {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3_89() {
    if (jj_scan_token(FALLTHROUGH)) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3_84() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_10()) {
    jj_scanpos = xsp;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3_14()) {
    jj_scanpos = xsp;
    if (jj_3_15()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(STRING_VALOR)) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(RETURN)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_86() {
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3_82() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3R_51() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_82()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(IMPORT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) return true;
    }
    return false;
  }

  private boolean jj_3_88() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_77() {
    if (jj_scan_token(PRINT)) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(CASE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_86()) {
    jj_scanpos = xsp;
    if (jj_3_87()) return true;
    }
    if (jj_scan_token(PUNTOS)) return true;
    if (jj_3_88()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_88()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3_85() {
    if (jj_scan_token(DEFECTO)) return true;
    if (jj_scan_token(PUNTOS)) return true;
    Token xsp;
    if (jj_3_84()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_84()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_83() {
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(SWITCH)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) return true;
    }
    if (jj_scan_token(LLAVEAPERTURA)) return true;
    if (jj_3_83()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_83()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_76() {
    if (jj_scan_token(PRINTLN)) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(ASIGNACIONCORTA)) return true;
    if (jj_scan_token(CORAPERTURA)) return true;
    if (jj_scan_token(INT_VALOR)) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(CORAPERTURA)) return true;
    if (jj_scan_token(INT_VALOR)) return true;
    if (jj_scan_token(CORCIERRE)) return true;
    return false;
  }

  private boolean jj_3_81() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(CORAPERTURA)) return true;
    return false;
  }

  private boolean jj_3_74() {
    if (jj_scan_token(GUIONBAJO)) return true;
    return false;
  }

  private boolean jj_3_80() {
    if (jj_scan_token(VAR)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(CORAPERTURA)) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_scan_token(VAR)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(CORAPERTURA)) return true;
    if (jj_scan_token(INT_VALOR)) return true;
    return false;
  }

  private boolean jj_3_62() {
    if (jj_scan_token(DIFERENTE)) return true;
    return false;
  }

  private boolean jj_3_79() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(ASIGNACIONCORTA)) return true;
    if (jj_scan_token(CORAPERTURA)) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_3R_62()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_3R_61()) return true;
    return false;
  }

  private boolean jj_3R_27() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_61() {
    if (jj_scan_token(IGUAL)) return true;
    return false;
  }

  private boolean jj_3_73() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(PUNTO)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_76()) {
    jj_scanpos = xsp;
    if (jj_3_77()) return true;
    }
    if (jj_scan_token(PAPERTURA)) return true;
    return false;
  }

  private boolean jj_3_75() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_scan_token(FOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_73()) {
    jj_scanpos = xsp;
    if (jj_3_74()) return true;
    }
    if (jj_scan_token(COMA)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3_53() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3_72() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(LLAVEAPERTURA)) return true;
    Token xsp;
    if (jj_3_72()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_72()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_58() {
    if (jj_scan_token(ASIGNACION)) return true;
    return false;
  }

  private boolean jj_3_45() {
    if (jj_scan_token(DECREMENTO)) return true;
    return false;
  }

  private boolean jj_3_71() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(FOR)) return true;
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3_69() {
    if (jj_scan_token(FOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(59)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) return true;
    }
    return false;
  }

  private boolean jj_3_60() {
    if (jj_scan_token(MENOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_58()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_65() {
    if (jj_scan_token(BITXOR)) return true;
    return false;
  }

  private boolean jj_3_68() {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(LLAVEAPERTURA)) return true;
    return false;
  }

  private boolean jj_3_70() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(FOR)) return true;
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3_67() {
    if (jj_scan_token(FOR)) return true;
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3_52() {
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3_66() {
    if (jj_scan_token(FOR)) return true;
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_3R_60()) return true;
    return false;
  }

  private boolean jj_3_44() {
    if (jj_scan_token(INCREMENTO)) return true;
    return false;
  }

  private boolean jj_3_64() {
    if (jj_scan_token(BITOR)) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_3R_59()) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_58()) return true;
    return false;
  }

  private boolean jj_3_56() {
    if (jj_scan_token(NOT)) return true;
    return false;
  }

  private boolean jj_3_57() {
    if (jj_scan_token(ASIGNACION)) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_3R_57()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3_43() {
    if (jj_scan_token(MOD)) return true;
    return false;
  }

  private boolean jj_3_51() {
    if (jj_3R_36()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_52()) {
    jj_scanpos = xsp;
    if (jj_3_53()) return true;
    }
    return false;
  }

  private boolean jj_3R_33() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_63()) {
    jj_scanpos = xsp;
    if (jj_3_64()) {
    jj_scanpos = xsp;
    if (jj_3_65()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_55() {
    if (jj_scan_token(OR)) return true;
    return false;
  }

  private boolean jj_3_63() {
    if (jj_scan_token(BITAND)) return true;
    return false;
  }

  private boolean jj_3R_53() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_59()) {
    jj_scanpos = xsp;
    if (jj_3_60()) {
    jj_scanpos = xsp;
    if (jj_3_61()) {
    jj_scanpos = xsp;
    if (jj_3_62()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3_59() {
    if (jj_scan_token(MAYOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_57()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_39() {
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_36() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_54()) {
    jj_scanpos = xsp;
    if (jj_3_55()) {
    jj_scanpos = xsp;
    if (jj_3_56()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_54() {
    if (jj_scan_token(AND)) return true;
    return false;
  }

  private boolean jj_3_47() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_3R_29()) return true;
    if (jj_3R_53()) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_49() {
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3_42() {
    if (jj_scan_token(MULTIPLICACION)) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_3R_37()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_51()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_18() {
    if (jj_scan_token(CORAPERTURA)) return true;
    if (jj_scan_token(INT_VALOR)) return true;
    if (jj_scan_token(CORCIERRE)) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3_32() {
    if (jj_scan_token(ASIGNACIONRESTA)) return true;
    return false;
  }

  private boolean jj_3_50() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(ELSE)) return true;
    if (jj_scan_token(LLAVEAPERTURA)) return true;
    Token xsp;
    if (jj_3_50()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_50()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_46() {
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3_37() {
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3_41() {
    if (jj_scan_token(RESTA)) return true;
    return false;
  }

  private boolean jj_3_48() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(IF)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_46()) {
    jj_scanpos = xsp;
    if (jj_3_47()) return true;
    }
    if (jj_scan_token(LLAVEAPERTURA)) return true;
    if (jj_3_48()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_48()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_34() {
    if (jj_3R_31()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public GramaticaTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[89];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Gramatica(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Gramatica(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GramaticaTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Gramatica(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new GramaticaTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Gramatica(GramaticaTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GramaticaTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[63];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 63; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 89; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
            case 36: jj_3_37(); break;
            case 37: jj_3_38(); break;
            case 38: jj_3_39(); break;
            case 39: jj_3_40(); break;
            case 40: jj_3_41(); break;
            case 41: jj_3_42(); break;
            case 42: jj_3_43(); break;
            case 43: jj_3_44(); break;
            case 44: jj_3_45(); break;
            case 45: jj_3_46(); break;
            case 46: jj_3_47(); break;
            case 47: jj_3_48(); break;
            case 48: jj_3_49(); break;
            case 49: jj_3_50(); break;
            case 50: jj_3_51(); break;
            case 51: jj_3_52(); break;
            case 52: jj_3_53(); break;
            case 53: jj_3_54(); break;
            case 54: jj_3_55(); break;
            case 55: jj_3_56(); break;
            case 56: jj_3_57(); break;
            case 57: jj_3_58(); break;
            case 58: jj_3_59(); break;
            case 59: jj_3_60(); break;
            case 60: jj_3_61(); break;
            case 61: jj_3_62(); break;
            case 62: jj_3_63(); break;
            case 63: jj_3_64(); break;
            case 64: jj_3_65(); break;
            case 65: jj_3_66(); break;
            case 66: jj_3_67(); break;
            case 67: jj_3_68(); break;
            case 68: jj_3_69(); break;
            case 69: jj_3_70(); break;
            case 70: jj_3_71(); break;
            case 71: jj_3_72(); break;
            case 72: jj_3_73(); break;
            case 73: jj_3_74(); break;
            case 74: jj_3_75(); break;
            case 75: jj_3_76(); break;
            case 76: jj_3_77(); break;
            case 77: jj_3_78(); break;
            case 78: jj_3_79(); break;
            case 79: jj_3_80(); break;
            case 80: jj_3_81(); break;
            case 81: jj_3_82(); break;
            case 82: jj_3_83(); break;
            case 83: jj_3_84(); break;
            case 84: jj_3_85(); break;
            case 85: jj_3_86(); break;
            case 86: jj_3_87(); break;
            case 87: jj_3_88(); break;
            case 88: jj_3_89(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
